import '@testing-library/jest-dom';

// Mock window.api for all renderer tests
const noop = () => () => {}; // returns unsubscribe fn

window.api = {
  getTracks: vi.fn().mockResolvedValue([]),
  getTrackIds: vi.fn().mockResolvedValue([]),
  getPlaylists: vi.fn().mockResolvedValue([]),
  getPlaylist: vi.fn().mockResolvedValue(null),
  createPlaylist: vi.fn().mockResolvedValue(1),
  renamePlaylist: vi.fn().mockResolvedValue(undefined),
  updatePlaylistColor: vi.fn().mockResolvedValue(undefined),
  deletePlaylist: vi.fn().mockResolvedValue(undefined),
  addTracksToPlaylist: vi.fn().mockResolvedValue(undefined),
  removeTrackFromPlaylist: vi.fn().mockResolvedValue(undefined),
  reorderPlaylist: vi.fn().mockResolvedValue(undefined),
  getPlaylistsForTrack: vi.fn().mockResolvedValue([]),
  selectAudioFiles: vi.fn().mockResolvedValue([]),
  importAudioFiles: vi.fn().mockResolvedValue([]),
  reanalyzeTrack: vi.fn().mockResolvedValue({ ok: true }),
  removeTrack: vi.fn().mockResolvedValue({ ok: true }),
  adjustBpm: vi.fn().mockResolvedValue([]),
  exportPlaylistAsM3U: vi.fn().mockResolvedValue({ canceled: true }),
  getSetting: vi.fn().mockResolvedValue(null),
  setSetting: vi.fn().mockResolvedValue(undefined),
  normalizeLibrary: vi.fn().mockResolvedValue({ updated: 0 }),
  getLibraryPath: vi.fn().mockResolvedValue('/tmp/audio'),
  moveLibrary: vi.fn().mockResolvedValue({ moved: 0, total: 0 }),
  openDirDialog: vi.fn().mockResolvedValue(null),
  getDepVersions: vi.fn().mockResolvedValue({}),
  checkDepUpdates: vi.fn().mockResolvedValue({}),
  updateAllDeps: vi.fn().mockResolvedValue(undefined),
  clearLibrary: vi.fn().mockResolvedValue(undefined),
  clearUserData: vi.fn().mockResolvedValue(undefined),
  getLogDir: vi.fn().mockResolvedValue('/tmp/logs'),
  openLogDir: vi.fn().mockResolvedValue(undefined),
  log: vi.fn(),
  onTrackUpdated: vi.fn().mockImplementation(noop),
  onLibraryUpdated: vi.fn().mockImplementation(noop),
  onPlaylistsUpdated: vi.fn().mockImplementation(noop),
  onOpenSettings: vi.fn().mockImplementation(noop),
  onDepsProgress: vi.fn().mockImplementation(noop),
  onMoveLibraryProgress: vi.fn().mockImplementation(noop),
  onExportM3UProgress: vi.fn().mockImplementation(noop),
};
